controller_manager:
  ros__parameters:
    update_rate: 500
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_state_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE
    interface_name: position
    
    command_interface: 
      -position
    state_interface:
      -position
      -velocity
